apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Настройки Django
  SECRET_KEY: "django-insecure-change-me-please"
  DEBUG: "1"
  ALLOWED_HOSTS: "*"
  
  POSTGRES_DB: "praktika"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
  

  DB_NAME: "praktika"
  DB_USER: "postgres"
  DB_PASSWORD: "12345"
  DB_HOST: "db"
  DB_PORT: "5432" 